Add debug and strict build checks
For some reason, v0.19.1 is marked as dirty although have not been
able to reproduce. Adding stricter behavior + debug in case it
happens again.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -19,10 +19,25 @@ if [ -z "${arch_list:-}" ]; then
   arch_list="amd64"
 fi
 
-mkdir -p tmp
+commit=$( git rev-parse HEAD | cut -c-10 )
 
-commit=$( git rev-parse HEAD | cut -c-10 )$( git diff-index --quiet HEAD -- || echo "+dirty" )
+if [[ $( git clean -dnx | wc -l ) -gt 0 ]] ; then
+  commit="${commit}+dirty"
+
+  if [[ "${version}" != "0.0.0" ]]; then
+    echo "ERROR: building an official version requires a clean repository"
+    echo "WARN: refusing to clean repository"
+    git clean -dnx
+
+    exit 1
+  fi
+fi
+
+mkdir -p tmp
+  
 built=$( date -u +%Y-%m-%dT%H:%M:%S+00:00 )
+
+echo "building ${version} (commit ${commit}; built ${built})"
 
 export CGO_ENABLED=0
 
